### ISSUE TITLE
Problem with Authentication/Association to AP

### ISSUE THREAD

**Issue by CapitanShinChan** [securestate/eapeak#1]
Hi!

I was using eapeak during a pentest a week ago, but it didn't work properly. The Wireless State Machine nearly always doesn't complete the Authentication/Association process with the AP, sometimes it's because it doesn't get the Authentication/Association Response.

But debugging with Wireshark or tcpdump using another interface, I can see that the AP sends the Authentication/Association frames, but there are not processed by eapscan. Could it be a problem related the scapy sniff() function, which could me lossing some frames?

I've tried with different USB WiFi cards.

Here is some example output:

10:00:50 root@KaliMero eapeak master ? ./eapscan -e WLAN_XY -b 60:A4:4C:69:D2:48 -i mon0 -c 6 -V                 
[*] Verbose output has been enabled
[*] Checking Connection To AP
[*] Verbose: using source MAC address: 00:93:a2:a9:8f:97 for testing connections
L2socket created?

[-] Verbose: did not receive a reply to the authentication request
.
[*] Verbose: using source MAC address: 00:17:f3:f8:aa:bd for testing connections
L2socket created?
L2socket created?

[-] Verbose: did not receive a reply to the association request
.
[*] Verbose: using source MAC address: 00:6b:fa:0f:fb:c3 for testing connections
L2socket created?

[-] Verbose: did not receive a reply to the authentication request
.
[-] Connection Attempts Failed
[-] Now Exiting...

**Comment by CapitanShinChan** [comment]
The message "L2socket created?" is a print that I've used for debugging purposes :P

**Comment by zeroSteiner** [comment]
I've known about the unstable association process that's used in eapscan for about as long as the tool has existed. I need to take a look again to see if I can make it more reliable at some point.

**Comment by CapitanShinChan** [comment]
I've been deeping in your code (and scapy's too) looking for the problem origin.

One possible reason could be that the callback function defined for stopping the sniffing process is taking too much time, so meanwhile some frames are lost (maybe because the Rx buffer is full?). I've tried to apply some filters like tcpdump does (tested "raw" and "cooked" filters) but it didn't fix the problem (they were not even properly working).

If you have any ideas, let me know, I'll be happy to help :smile:

**Comment by zeroSteiner** [comment]
Absolutely, thank you for trying to help. If you figure anything out just make a pull request and we'll get it fixed.

**Comment by zeroSteiner** [comment]
We've made a bunch of improvements to eapscan over the past couple of weeks (see PRs #3, #4). I know this issue is pretty old but I wanted to let you know that it should be resolved now.
